
package org.examle.soapclient;

import com.sun.xml.ws.runtime.config.ObjectFactory;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EducationService", targetNamespace = "http://ws.SoapService.soapservice.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ducationService {


    /**
     * 
     * @param surname
     * @param name
     * @return
     *     returns java.util.List<org.examle.soapclient.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getalluser", targetNamespace = "http://ws.SoapService.soapservice.example.org/", className = "org.examle.soapclient.Getalluser")
    @ResponseWrapper(localName = "getalluserResponse", targetNamespace = "http://ws.SoapService.soapservice.example.org/", className = "org.examle.soapclient.GetalluserResponse")
    @Action(input = "http://ws.SoapService.soapservice.example.org/EducationService/getalluserRequest", output = "http://ws.SoapService.soapservice.example.org/EducationService/getalluserResponse")
    public List<User> getalluser(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "surname", targetNamespace = "")
        String surname);

    /**
     * 
     * @param name
     * @return
     *     returns org.examle.soapclient.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getuser", targetNamespace = "http://ws.SoapService.soapservice.example.org/", className = "org.examle.soapclient.Getuser")
    @ResponseWrapper(localName = "getuserResponse", targetNamespace = "http://ws.SoapService.soapservice.example.org/", className = "org.examle.soapclient.GetuserResponse")
    @Action(input = "http://ws.SoapService.soapservice.example.org/EducationService/getuserRequest", output = "http://ws.SoapService.soapservice.example.org/EducationService/getuserResponse")
    public User getuser(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
