drop table messages;
drop table message_types;
drop table users;

create table if not exists users(user_id serial primary key,username varchar(50) not null,email varchar(100) unique not null,created_at timestamp default current_timestamp);
create table message_types(message_type_id serial primary key,type_name varchar(50) not null,description text);
create table messages(message_id serial primary key,sender_id int not null,receiver_id int not null,message_type_id int ,content text ,sent_at timestamp default current_timestamp,foreign key(sender_id)references users(user_id) on delete cascade,foreign key(receiver_id)references users(user_id)on delete cascade,foreign key(message_type_id)references message_types(message_type_id)on delete set null);
insert into message_types(type_name,description)values('text','Simple text messages'),('image','Image-based messages'),('video','video-based messages'),('audio','audio-based messages');
insert into users(username,email)values('user1','user1@example.com'),('user2','user2@example.com'),('user3','user3@example.com'),('user4','user4@example.com');
insert into users(username,email)values('user5','user5@example.com');
insert into messages(sender_id,receiver_id,message_type_id,content)values(1,2,1,'Hello user2,how are you?'),(2,1,1,'I am fine,thank you!'),(1,3,2,'Check this cool image.'),(3,4,null,'Here is a video for you.'),(4,5,1,'Good morning!'),(5,1,1,'Good morning to you too!'),(2,3,null,'What is the status of our project?'),(3,2,1,'Where are almost done.'),(4,1,2,'I found a useful diagram for our report.'),(1,4,1,'Thanks for sharing!'),(5,3,3,'This video might be helpful for your presentation.'),(3,5,1,'Got it,thanks!'),(2,4,1,'What time is our meeting?'),(4,2,1,'It''s at 3 PM.'),(1,5,2,'Attached is the draft of the proposal.'),(5,2,1,'I''ll review it shortly'),(4,3,3,'Watch this for a better understanding.'),(2,1,1,'Do you need anything else?'),(1,2,2,'Not at the moment,thank you.'),(3,4,1,'Can we discuss the budget later today?'),(4,3,1,'Sure,let''s do it after lunch.'),(5,1,1,'Can you share the project files?'),(1,5,2,'Here are the files you requested.'),(2,3,1,'Let''s wrap this up soon.'),(3,2,3,'This resource might be helpfull.'),(4,5,1,'Thanks for the update.'),(5,4,1,'You''re welcome!'),(1,3,3,'Here is a tutorial video for you.'),(3,1,1,'This is very helpful,thank you!'),(2,5,2,'Attached are the updates charts.');
select *from message_types;
select *from users;
select * from messages;
--select * from messages left join message_types on messages.message_type_id=message_types.message_type_id left join users sender on messages.sender_id=sender.user_id left join users receiver on messages.receiver_id=receiver.user_id;
--select sender.username as sender,receiver.username as receiver ,messages.content,message_types.type_name,messages.sent_at from messages left join message_types on messages.message_type_id=message_types.message_type_id left join users sender on messages.sender_id=sender.user_id left join users receiver on messages.receiver_id=receiver.user_id where message_types.message_type_id=1;
--select sender.username as sender,receiver.username as receiver ,messages.content,message_types.type_name,messages.sent_at from messages left join message_types on messages.message_type_id=message_types.message_type_id left join users sender on messages.sender_id=sender.user_id left join users receiver on messages.receiver_id=receiver.user_id where messages.sender_id=1 or messages.receiver_id=1;
select sender.username as sender,receiver.username as receiver ,messages.content,message_types.type_name,messages.sent_at from messages left join message_types on messages.message_type_id=message_types.message_type_id left join users sender on messages.sender_id=sender.user_id left join users receiver on messages.receiver_id=receiver.user_id where (messages.sender_id=1 or messages.receiver_id=1) and (messages.receiver_id=2 or messages.sender_id=2) and(message_types.message_type_id=1);
select messages.*,message_types.type_name from messages left join message_types on messages.message_type_id=message_types.message_type_id where messages.message_type_id is not null;